#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
VERSION=$( cat VERSION )

docker run -it -v $DIR:/home/br-user/app docker.pkg.github.com/parasrah/nerves_system_rpi4/buildroots-pi4:$VERSION /bin/bash
