name: 'Generate Releases'
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(cat VERSION)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: parasrah/nerves_system_rpi4/buildroots-pi4
          username: parasrah
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }},${{ github.sha }}"

  # this is currently blocked as there is no way to download public images without authentication...
  # system:
  #   runs-on: ubuntu-18.04
  #   needs: docker
  #   container: "docker.pkg.github.com/parasrah/buildroots:${{ github.sha }}"
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Get dependencies
  #       run: mix deps.get
  #     - name: Build system
  #       run: mix compile
